
function getDe() {


var selector = document.getElementById('qw');
var value = selector[selector.selectedIndex].value;

if(value == 1 ) {
  document.getElementById("bv1").innerHTML = "Understand what your responsibilities are and how these contribute to the priorities of your team.  Consider the varied impact your work could have on individuals with different needs and from other backgrounds. Gather information from both inside and outside of the organisation to inform your area of work"
  document.getElementById("bv2").innerHTML = "Review ways of working and suggest improvements, including how to make full use of new digital technologies. Learn new procedures and help colleagues to do the same. Query any issues that arise from changes in a suitable way. Respond in an effective and appropriate manner when emergencies arise."
  document.getElementById("bv3").innerHTML = "Use guidance, analyse relevant information and ask colleagues for input to support decision making. Identify and deal with any errors or gaps in information before making a decision. Consider the diverse needs of those affected by decisions and how it will impact them. Provide advice and feedback to support others in making accurate decisions. Ask others to clarify decisions when confused and query any issues that arise constructively."
  document.getElementById("bv4").innerHTML = "Show enthusiasm for your work and take personal accountability for your role. Demonstrate responsibility for your own objectives. Act in a fair, inclusive and respectful way when dealing with others. Be considerate and understanding of other people’s points of view. Understand and support the objectives of the wider team. Demonstrate consideration of the wider consequences of own actions."
  document.getElementById("bv5").innerHTML = "Put forward your views in a clear, constructive and considerate manner. Use an appropriate method of communication for each person such as an email, telephone call or face-to-face, taking into consideration their individual needs. Use plain and simple language, being careful to check written work for errors. Consider the impact of language used on different groups of stakeholders. Remain honest and truthful when explaining opinions. Listen and ask questions to ensure your understanding."
  document.getElementById("bv6").innerHTML = "Proactively contribute to the work of the whole team and remain open to taking on new and different roles. Get to know your colleagues and build supportive relationships. Listen to alternative perspectives and needs, responding sensitively and checking understanding where necessary. Ask for help when needed and support others when the opportunity arises. Be aware of the need to consider your own wellbeing and that of your colleagues. Understand that bullying, harassment and discrimination are unacceptable."
  document.getElementById("bv7").innerHTML = "Identify gaps in your skills and knowledge and make plans of how to develop these. Take time to achieve development objectives. Listen to and act on feedback from colleagues to find areas you can develop. Share knowledge and skills learnt with colleagues to contribute to the learning and development of the whole team."
  document.getElementById("bv8").innerHTML = "Gain a clear understanding of customers’ needs and expectations. Plan, organise and manage your own time to deliver a high quality service which gives taxpayers a good return for their money. Act to prevent problems by identifying issues, reporting them and providing solutions. Keep customers and all colleagues up to date with progress. Show customers where to access relevant information and support that will help them to use services more effectively."
  document.getElementById("bv9").innerHTML = "Always work with focus and pace to get the job done on time and to a high standard. Follow the relevant policies, procedures and rules that apply to the job. Use own knowledge and expertise to organise work. Keep focused on delivery and take responsibility for the quality of work produced. Keep a consistent level of personal performance. Keep managers and stakeholders updated on how work is progressing."
}

if(value == 2 ) {
  document.getElementById("bv1").innerHTML = "Understand how your work and the work of your team supports wider objectives and meets the diverse needs of stakeholders. Keep up to date with the issues that affect your work area. Take a keen interest in expanding knowledge in areas related to your work. Focus on overall goals and not just specific tasks to meet priorities."
  document.getElementById("bv2").innerHTML = "Regularly review own and team’s work and take the initiative to suggest ideas to make improvements. Give feedback on changes in a constructive manner. Take a positive, open approach to the possibility of change and encourage others to do the same. Help others to understand changes and the reasons they are being put in place. Identify and act on the effects changes are having on your role and that of the team. Look for ways to use technology to achieve efficient and effective results. Consider accessibility needs of the diverse range of end users."
  document.getElementById("bv3").innerHTML = "Take responsibility for making effective and fair decisions, in a timely manner. Analyse and research further information to support decisions. Talk to relevant people to get advice and information when unsure how to proceed. Explain how decisions have been reached in a clear and concise way, both verbally and in writing. Demonstrate the consideration of all options, costs, risks and wider implications, including the diverse needs of end users and any accessibility requirements."
  document.getElementById("bv4").innerHTML = "Show pride and passion for your work and positive, inclusive engagement with your team. Understand your areas of responsibility and display awareness of the wider impact of your actions. Proactively role model and promote an inclusive workplace, promptly dealing with inappropriate language and behaviours when they arise, including any instances of discrimination or misconduct. Give praise and credit to colleagues and stakeholders where appropriate."
  document.getElementById("bv5").innerHTML = "Communicate clearly and concisely both orally and in writing. Take time to consider the best communication channel to use for the audience, including making the best of digital resources and considering value for money. Interact with others in an enthusiastic way. Express ideas clearly and with respect for others. Listen to and value different ideas, views and ways of working. Respond constructively and objectively to comments and questions. Handle challenging conversations with confidence and sensitivity."
  document.getElementById("bv6").innerHTML = "Develop a range of contacts outside own team and identify opportunities to share knowledge, information and learning. Show genuine interest when listening to others. Contribute to an inclusive working environment where all opinions and challenges are listened to and all individual needs are taken into account. Ensure it is clear that bullying, harassment and discrimination are unacceptable. Offer support and help to colleagues when in need, including consideration of your own and their wellbeing. Change ways of working to aid cooperation within and between teams in order to achieve results."
  document.getElementById("bv7").innerHTML = "Identify gaps in own and team’s skills and knowledge. Set and consistently meet development objectives. Seek learning opportunities. Support the development plans of all colleagues, recognising how diversity of experience/background can help to build an inclusive team culture. Consider the contributions of all team members and delegate work to aid the learning and development of all. Encourage and listen to developmental feedback from colleagues."
  document.getElementById("bv8").innerHTML = "Work with customers to understand their needs and expectations. Create clear plans and set priorities which meet the needs of both the customer and the business. Clearly explain to customers what can be done. Keep colleagues and stakeholders fully informed of plans, possibilities and progress. Identify common problems that affect service, report them and find possible solutions. Deliver good customer service which balances quality and cost effectiveness."
  document.getElementById("bv9").innerHTML = "Regularly review the success of activities in the team to identify barriers to progress or challenging objectives. Identify who and what is required to ensure success, set clear goals and areas of responsibility and continually assess workloads considering individual needs. Follow relevant policies, procedures and legislation to complete your work. Ensure colleagues have the correct tools and resources available to them to do their jobs. Have a positive and focused attitude to achieving outcomes, despite any setbacks. Regularly check performance against objectives, making suggestions for improvement or taking corrective action where necessary. Ensure that colleagues are supported where tasks are challenging."
}

if(value == 3 ) {
  document.getElementById("bv1").innerHTML = "Understand the strategic drivers for your area of work. Align activities to contribute to wider organisational priorities. Remain alert to emerging issues and trends which might impact your work area. Seek out and share experiences to develop knowledge of the team’s business area. Understand how the strategies and activities of the team create value and meet the diverse needs of all stakeholders."
  document.getElementById("bv2").innerHTML = "Work with others to identify areas for improvement and simplify processes to use fewer resources. Use technology where possible to increase efficiency. Encourage ideas for change from a wide range of sources. Clearly explain the reasons for change to colleagues and how to implement them, supporting individuals with different needs to adapt to change. Encourage an environment where colleagues know that they can challenge decisions and issues safely. Take managed risks by fully considering the varied impacts changes could have on the diverse range of end users."
  document.getElementById("bv3").innerHTML = "Understand own level of responsibility and empower others to make decisions where appropriate. Analyse and use a range of relevant, credible information from internal and external sources to support decisions. Invite challenge and where appropriate involve others in decision making. Display confidence when making difficult decisions, even if they prove to be unpopular. Consult with others to ensure the potential impacts on end users have been considered. Present strong recommendations in a timely manner outlining the consideration of other options, costs, benefits and risks."
  document.getElementById("bv4").innerHTML = "Ensure colleagues and stakeholders have a clear understanding of objectives, activities and time-frames. Take into account different individual needs, views, and ideas, championing inclusion and equality of opportunity for all. Consider the impacts of own and team’s activities on stakeholders and end users. Role-model commitment and satisfaction with role. Recognise and praise the achievements of others to drive positivity within the team. Effectively manage conflict, misconduct and non-inclusive behaviour, raising with senior managers where appropriate."
  document.getElementById("bv5").innerHTML = "Communicate in a straightforward, honest and engaging manner, choosing appropriate styles to maximise understanding and impact. Encourage the use of different communication methods, including digital resources and highlight the benefits, including ensuring cost effectiveness. Ensure communication has a clear purpose and takes into account people’s individual needs. Share information as appropriate and check understanding. Show positivity and enthusiasm towards work, encouraging others to do the same. Ensure that important messages are communicated with colleagues and stakeholders respectfully, taking into consideration the diversity of interests."
  document.getElementById("bv6").innerHTML = "Encourage joined up team work within own team and across other groups. Establish professional relationships with a range of stakeholders. Collaborate with these to share information, resources and support. Invest time to develop a common focus and genuine positive team spirit where colleagues feel valued and respect one another. Put in place support for the wellbeing of individuals within the team, including consideration of your own needs. Make it clear to all team members that bullying, harassment and discrimination are unacceptable. Actively seek and consider input of people from diverse backgrounds and perspectives."
  document.getElementById("bv7").innerHTML = "Identify capability gaps for self and team. Ensure development objectives are set and achieved to address any gaps and enable delivery of current and future work. Take time to coach, mentor and develop other colleagues to support succession planning. Promote inclusiveness by respecting different personal needs in the team and use these to develop others. Reflect on own work, continuously seek and act on feedback to improve own and team’s performance."
  document.getElementById("bv8").innerHTML = "Develop, implement, maintain and review systems and services to ensure delivery of professional excellence. Work with stakeholders to set priorities, objectives and timescales. Successfully deliver high quality outcomes that meet the customers’ needs and gives value for money. Identify risks and resolve issues efficiently. Involve a diverse range of colleagues, stakeholders and delivery partners in developing suggestions for improvements. Establish ways to find and respond to feedback from customers about the services provided."
  document.getElementById("bv9").innerHTML = "Show a positive approach to keeping the whole team’s efforts focused on the top priorities. Promote a culture of following the appropriate procedures to ensure results are achieved on time whilst still enabling innovation. Ensure the most appropriate resources are available for colleagues to use to do their job effectively. Regularly monitor your own and team’s work against milestones ensuring individual needs are considered when setting tasks. Act promptly to reassess workloads and priorities when there are conflicting demands to maintain performance. Allow individuals the space and authority to meet objectives, providing additional support where necessary, whilst keeping overall responsibility."
}

if(value == 4 ) {
  document.getElementById("bv1").innerHTML = "Develop and maintain an understanding of economic, social, political, environmental and technological developments to ensure activity is relevant. Ensure plans and activities in your area of work reflect wider strategic priorities and communicate effectively with senior leaders to influence future strategies. Adopt a government wide perspective to ensure alignment of activity and policy. Bring together views, perspectives and diverse needs of stakeholders to gain a broader understanding of the issues surrounding policies and activities."
  document.getElementById("bv2").innerHTML = "Encourage, recognise and share innovative ideas from a diverse range of colleagues and stakeholders. Give people space to take initiative and praise them for their creativity. Create an environment where people feel safe to challenge and know their voice will be heard. Make changes which add value and clearly articulate how changes will benefit the business. Understand and identify the role of technology in public service delivery and policy implementation. Consider the full impact of implementing changes on culture, structure, morale and the impacts on the diverse range of end users, including accessibility needs. Identify early signs that things are going wrong and respond promptly. Provide constructive challenge to senior management on change proposals."
  document.getElementById("bv3").innerHTML = "Clarify your own understanding and stakeholder needs and expectations, before making decisions. Ensure decision making happens at the right level, not allowing unnecessary bureaucracy to hinder delivery. Encourage both innovative suggestions and challenge from others, to inform decision making. Analyse and accurately interpret data from various sources to support decisions. Find the best option by identifying positives, negatives, risks and implications. Present reasonable conclusions from a wide range of complex and sometimes incomplete evidence. Make decisions confidently even when details are unclear or if they prove to be unpopular."
  document.getElementById("bv4").innerHTML = "Promote diversity, inclusion and equality of opportunity, respecting difference and external experience. Welcome and respond to views and challenges from others, despite any conflicting pressures to ignore or give in to them. Stand by, promote or defend own and team’s actions and decisions where needed. Seek out shared interests beyond own area of responsibility, understanding the extent of the impact actions have on the organisation. Inspire and motivate teams to be fully engaged in their work and dedicated to their role."
  document.getElementById("bv5").innerHTML = "Communicate with others in a clear, honest and enthusiastic way in order to build trust. Explain complex issues in a way that is easy to understand. Take into account people’s individual needs. Deliver difficult messages with clarity and sensitivity, being persuasive when required. Consider the impact of the language used. Remain open-minded and impartial in discussions, whilst respecting the diverse interests and opinions of others. Introduce different methods for communication, including making the most of digital resources whilst getting value for money. Monitor the effectiveness of own and team communications and take action to improve where necessary."
  document.getElementById("bv6").innerHTML = "Actively build and maintain a network of colleagues and contacts to achieve progress on shared objectives. Challenge assumptions while being willing to compromise if beneficial to progress. Build strong interpersonal relationships and show genuine care for colleagues. Ensure consideration and support for the wellbeing of yourself and individuals throughout the team. Understand the varying needs of the team to ensure they are supported and their experiences are utilised. Create an inclusive working environment where all opinions and challenges are taken into account and bullying, harassment and discrimination are unacceptable. Remain available and approachable to all colleagues and be receptive to new ideas."
  document.getElementById("bv7").innerHTML = "Prioritise and role-model continuous self-learning and development. Identify areas individuals and teams need to develop in order to achieve future objectives. Support colleagues to take responsibility for their own learning and development. Ensure that development opportunities are available for all individuals regardless of their background or desire to achieve promotion. Ensure individuals take full advantage of learning and development opportunities available to them, including workplace based learning. Encourage discussions within and between teams to learn from each other’s experiences and change organisational plans and processes accordingly."
  document.getElementById("bv8").innerHTML = "Demonstrate positive customer service by understanding the complexity and diversity of customer needs and expectations. Deliver a high quality, efficient and cost effective service by considering a broad range of methods for delivery. Ensure full consideration of new technologies, accessibility and costings. Make clear, practical and manageable plans for service delivery. Ensure adherence to legal, regulatory and security requirements in service delivery. Proactively manage risks and identify solutions. Establish how the business area compares to industry best practice. Create regular opportunities for colleagues, stakeholders, delivery partners and customers to help improve the quality of service."
  document.getElementById("bv9").innerHTML = "Ensure everyone clearly understands and owns their roles, responsibilities and business priorities. Give honest, motivating and enthusiastic messages about priorities, objectives and expectations to get the best out of people. Comply with legal, regulatory and security requirements in service delivery. Set out clear processes and standards for managing performance at all levels. Ensure delivery of timely quality outcomes, through providing the right resources to do the job, reviewing and adjusting performance expectations and rewarding success. Maintain own levels of performance in challenging circumstances and encourage others to do the same."
}

if(value == 5 ) {
  document.getElementById("bv1").innerHTML = "Anticipate the long-term impact on the Department of economic, political, environmental, social and technological developments, at both national and international levels. Create joined up strategies that put into practice and support the Government’s vision for the future. Identify and shape how your work area fits within and supports the priorities of the organisation. Develop an in-depth insight into customers, services, communities and markets affected by your work areas and the wider public sector context. Ensure work is in the national interest whilst meeting the diverse needs of all end users."
  document.getElementById("bv2").innerHTML = "Challenge the way things have always been done and suggest improvements, learning from experience. Seek, encourage and recognise initiative and imaginative ideas from a wide range of people. Promote an environment where all colleagues feel safe to challenge. Encourage measured risk taking and innovation to deliver better approaches and services. Implement changes that transform flexibility, responsiveness and quality of service. Ensure changes add value to the business and express clearly how and why changes are necessary. Lead the transformation towards using digital technologies ensuring full consideration of accessibility needs and the diverse range of end users. Manage change effectively and respond promptly to critical events. Constructively challenge changes which are unhelpful."
  document.getElementById("bv3").innerHTML = "Act decisively and make bold, unbiased decisions at a strategic level. Make sense of a wide range of political and national pressures and influences to develop strategies which meet organisational goals. Clearly communicate the purpose and reasons for recommendations and decisions. Consult with others where necessary to ensure decisions meet the diverse needs of the end users. Accept and respond to challenge constructively. Clearly recommend the best option articulating risks and impacts on economic, environmental, political and social factors."
  document.getElementById("bv4").innerHTML = "Remain visible and approachable to all colleagues and stakeholders. Actively promote the reputation of the organisation with pride, both internally and externally. Display passion and enthusiasm for the work, helping to inspire colleagues and stakeholders to fully engage with the aims and long term vision. Embed a culture of inclusion and equal opportunity for all, where the diversity of individuals’ backgrounds and experiences are valued and respected. Work to influence the strategy, direction and culture to increase effectiveness."
  document.getElementById("bv5").innerHTML = "Implement communication strategies which ensure effective communications are embedded and take account of people’s individual needs. Embed a culture where there is a wide ranging use of the infrastructure in place to support varied communication methods which deliver value for money. Communicate in a straightforward, honest and truthful way with consideration for the impact of the method used. Communicate with conviction and clarity in the face of tough negotiations or challenges. Respect and consider the diversity of the audience when giving messages and deliver these appropriately. Influence external partners, stakeholders and customers successfully securing mutually beneficial outcomes."
  document.getElementById("bv6").innerHTML = "Proactively create, maintain and promote a strong network of contacts across the organisation and externally. Embed an inclusive culture of creating positive and supportive teams who consider the diverse needs and feelings of other colleagues. Ensure consideration and support for the wellbeing of all individuals across the organisation. Set out clear expectations that bullying, harassment, and discrimination are unacceptable. Encourage and establish mechanisms to share knowledge and resources across boundaries to support the business. Encourage teams to engage with a variety of delivery partners and stakeholders, listen to and act on their feedback."
  document.getElementById("bv7").innerHTML = "Provide a range of experiences to encourage development, talent and career management for all individuals. Role-model continuous self-learning and development, evaluate effectiveness and plan next steps. Ensure colleagues take responsibility for their own learning and development. Provide colleagues with opportunities to share their knowledge and skills with others to build organisational effectiveness. Share own expertise through coaching and mentoring to support teams to succeed. Create an inclusive environment from which all individuals can develop regardless of their needs or background. Deliver strategies to grow sustainable capability across all groups, including those with high potential and ensuring that the strategies tackle the imbalance in diversity."
  document.getElementById("bv8").innerHTML = "Clarify and articulate the diverse requirements of customers and delivery partners. Use customer insight to drive high quality and efficient service delivery which is a good investment of taxpayers money. Work collaboratively with customers and delivery partners to manage, monitor and deliver agreed outcomes. Identify areas for improvement and make appropriate changes to reach professional excellence. Break down complex aims into clear, practical and manageable plans. Identify the resource requirements to support implementation. Ensure risks are monitored and managed to prevent issues with service delivery wherever possible."
  document.getElementById("bv9").innerHTML = "Translate strategic priorities into clear outcome-focused objectives for managers and teams. Promote resilience and responsiveness in the organisation. Deliver against own objectives, while ensuring others take responsibility for their areas. Establish an inclusive culture which allows people space and authority to deliver their objectives whilst ensuring appropriate support is in place when needed. Give people credit for maintaining focus on priorities, while responding quickly to changing requirements. Act as a role model for delivery by showing efficiency and focus, while being open to new ideas and honest about challenges. Provide clarity about the action required to achieve results and address unexpected developments. Ensure all appropriate tools and resources are available for individuals to fulfill their job role."
}

if(value == 6 ) {
  document.getElementById("bv1").innerHTML = "Develop an in-depth insight into the dynamics and issues surrounding the Department and the Government. Understand political, economic, social, environmental and technological impact at both national and international levels. Establish where the Department sits within and aligns across the Civil Service. Ensure teams understand their role within the wider business. Shape the Department’s role and purpose in delivering civil service priorities which are in the national interest and meet the diverse needs of all stakeholders. Create clear long-term strategies focused on adding value to the nation and making real, lasting change beyond the Civil Service. Fully engage with senior leaders from across government to support strategic decision making."
  document.getElementById("bv2").innerHTML = "Constructively challenge bureaucratic decision making, resourcing structures and processes across the Civil Service. Strive to simplify approaches to create an effective organisation using digital technologies ensuring full consideration of accessibility needs and the diverse range of end users. Proactively champion and lead change, seeking innovative new approaches, policies and systems that add value to the organisation. Create a culture of innovation, flexibility and responsiveness enabling departments to swiftly respond to change. Have the confidence to take calculated risks to change how things are done. Establish an environment where all colleagues feel safe to challenge without fear. Consider the full impact of change on the organisational culture and wider government structures."
  document.getElementById("bv3").innerHTML = "Develop departmental or functional strategies and priorities while considering a wide range of political, national and international pressures. Manage and mitigate evaluated risks and options when making decisions. Demonstrate transparency around decisions and create a culture where others feel able to challenge decisions being made. Give unbiased evidence-led advice to Ministers and other senior officials based on extensive robust analysis. When required, be able to make unpopular decisions and defend them at the highest level. Ensure early and continued engagement with the right stakeholders when making recommendations or decisions. Emphasise the importance of considering the different needs of end users."
  document.getElementById("bv4").innerHTML = "Actively develop and protect the reputation of the Civil Service, creating a sense of pride and passion for public service. Present a clear and focused strategy with direction for the future. Act in ways that are highly visible, inspirational and credible at the most senior levels across and outside of the Civil Service. Create an inclusive environment where diversity is valued and there is equality of opportunity for all. Engage positively in debate and resolve ambiguities, gaining the best possible outcomes for the Department."
  document.getElementById("bv5").innerHTML = "Demonstrate and promote communicating with honesty, integrity, impartiality and objectivity. Ensure there is the infrastructure to support varied communication methods which are cost effective and keep up with advances in digital technology. Develop a culture where colleagues consider the individual needs of people when deciding how to communicate and understand the impacts of the chosen methods. Communicate purpose and direction with respect, clarity and enthusiasm. Overcome objections to gain acceptance of the vision and purpose of the Department. Use your influence to make a positive difference across the Civil Service and externally."
  document.getElementById("bv6").innerHTML = "Drive an inclusive and collaborative working culture which values diversity and encourages, openness, approachability and sensitivity. Ensure the wellbeing of all individuals is valued across the organisation. Confront issues and challenge assumptions at the highest levels, no matter how uncomfortable, in an assertive yet constructive way. Create a culture where bullying, harassment and discrimination are unacceptable. Build a strong diverse network of professional relationships across the highest levels of government and with Non-Executive Directors. Act for the wider good of the Civil Service by improving governance at board level to meet Civil Service objectives."
  document.getElementById("bv7").innerHTML = "Build a strong culture of continuous learning and knowledge sharing. Promote the importance of developing everyone to their full potential. Develop capability strategies that address equality of opportunity and value the diversity of all individuals. Develop and maintain an organisational commitment to empowering individuals to take responsibility for their own learning. Take a strategic perspective to identifying the capability needs of the organisation now and in the future. Be an outstanding mentor and coach to other senior individuals. Actively seek opportunities for reverse mentoring to increase your knowledge and insights of challenges faced by under-represented groups. Evaluate own effectiveness and plan ways to develop."
  document.getElementById("bv8").innerHTML = "Work across government to ensure delivery of professional excellence and expertise to customers. Ensure the Department has an in-depth and evolving understanding of the broad range of customers’ requirements. Establish and negotiate service levels and deliverables with delivery partners at a broad strategic level. Promote delivering value for money, emphasising a good return on tax payers money. Ensure all parts of the delivery chain fully understand the required outcomes for the customer. Ensure all colleagues and stakeholders involved in delivery are clear about the impacts of poor service and communication on the customer."
  document.getElementById("bv9").innerHTML = "Set and maintain a clear direction for the Department, with highly focused priorities and project and programme outcomes. Define and integrate clear structures, systems and resources across the Department which promote efficient service delivery. Swiftly adjust priorities as changing situations dictate. Enable the organisation to remain focused on core priorities irrespective of external challenges. Encourage, support and coach individuals and teams to keep focus on delivery. Drive a performance culture across the Department which gives teams the space and authority to deliver objectives, whilst holding them accountable for outcomes."
}

if(value == 0 ) {
  document.getElementById("bv1").innerHTML = ""
  document.getElementById("bv2").innerHTML = ""
  document.getElementById("bv3").innerHTML = ""
  document.getElementById("bv4").innerHTML = ""
  document.getElementById("bv5").innerHTML = ""
  document.getElementById("bv6").innerHTML = ""
  document.getElementById("bv7").innerHTML = ""
  document.getElementById("bv8").innerHTML = ""
  document.getElementById("bv9").innerHTML = ""
}

}



function FShidden() {
  var x = document.getElementById("FSSection")
  var yes = document.getElementById("FSyes")
  var no = document.getElementById("FSno")
  
  if(yes.checked  === true) {
    x.style.display = "block";
    
  }
  if(no.checked  === true) {
    x.style.display = "none";

  }
 
}

getDe()
FShidden()